### ISSUE TITLE
ModuleNotFoundError: No module named 'gloss.gloss_core'

### ISSUE THREAD

**Issue by pzh1202** [silviazuffi/gloss_skeleton#1]
First of all, thank you very much for your excellent work, but when I try to run it, he prompts the error as shown in the title. I am curious whether it is caused by my operation error or the missing file. I am looking forward to your answer.
`ModuleNotFoundError: No module named 'gloss.gloss_core'`

**Comment by SEU-PZH** [comment]
Sorry to bother you, I'm just getting started in this field, can you please tell me about when the file will be uploaded again？

**Comment by pzh1202** [comment]
Thank you so much, I have found it.

**Comment by silviazuffi** [comment]
Added
